[package]
name = "document-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
docx-rs = "0.4.17"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
serde_repr = "0.1.19"
